connector_server:
  endpoint:
    host: "0.0.0.0"
    port: 50051

logger:
  log_level: INFO
  enable_sql_query_logging: false

metrics_server:
  endpoint:
    host: "0.0.0.0"
    port: 8766

paging:
  bytes_per_page: 4194304
  prefetch_queue_capacity: 2

conversion:
  use_unsafe_converters: true
