connector_server:
  endpoint:
    host: "0.0.0.0"
    port: 2130

logger:
  log_level: DEBUG
  enable_sql_query_logging: true

metrics_server:
  endpoint:
    host: "0.0.0.0"
    port: 8767

pprof_server:
  endpoint:
    host: "0.0.0.0"
    port: 6060

paging:
  bytes_per_page: 4194304
  prefetch_queue_capacity: 2

conversion:
  use_unsafe_converters: true

data_source_default:  &data_source_default_var
  open_connection_timeout: 5s
  ping_connection_timeout: 5s
  exponential_backoff:
    initial_interval: 500ms
    randomization_factor: 0.5
    multiplier: 1.5
    max_interval: 20s
    max_elapsed_time: 1m

datasources:
  clickhouse:
    <<: *data_source_default_var
    pushdown:
      enable_timestamp_pushdown: false # YQ-4063
    
  greenplum:
    <<: *data_source_default_var
    pushdown:
      enable_timestamp_pushdown: true

  ms_sql_server:
    <<: *data_source_default_var
    pushdown:
      enable_timestamp_pushdown: false # YQ-4062

  mysql:
    <<: *data_source_default_var
    result_chan_capacity: 1024
    pushdown:
      enable_timestamp_pushdown: true

  postgresql:
    <<: *data_source_default_var
    pushdown:
      enable_timestamp_pushdown: true
    splitting:
      enabled: true
      table_physical_size_threshold_bytes: 104857600 #100 MB

  oracle:
    <<: *data_source_default_var
    pushdown:
      enable_timestamp_pushdown: false # YQ-3527

  mongodb:
    <<: *data_source_default_var
    count_docs_to_deduce_schema: 5
    object_id_yql_type: OBJECT_ID_AS_STRING

  redis:
    <<: *data_source_default_var
    count_docs_to_deduce_schema: 100

  ydb:
    <<: *data_source_default_var
    use_underlay_network_for_dedicated_databases: false
    mode: MODE_QUERY_SERVICE_NATIVE_ARROW
    pushdown:
      enable_timestamp_pushdown: true
    splitting:
      enabled_on_column_shards: true

observation:
  server:
    endpoint:
      host: "0.0.0.0"
      port: 8080
  storage:
    sqlite:
      path: /tmp/connector.sqlite
      gc_period: 1h
      request_ttl: 24h
